import test from 'node:test';
import assert from 'node:assert/strict';
import { GameEngine } from '../server/engine';
import { APARTMENT, canSee, walkable, movePoint } from '../shared/map';
const make=(count=1)=>{const e=new GameEngine();for(let i=1;i<=count;i++)e.add(`p${i}`,`Child ${i}`,{});e.start('p1');return e;};
function at(e:GameEngine,target:string,p='p1'){const o=APARTMENT.interactables.find(o=>o.id===target)!;const player=e.player(p);player.x=o.x;player.y=o.y;e.inspect(p,target);}
function act(e:GameEngine,target:string,action:string,value?:unknown,p='p1'){at(e,target,p);return e.act(p,target,action,value);}
function bedroom(e:GameEngine){at(e,'toyHouse');act(e,'seat','collectSeat');act(e,'legs','collectLegs');act(e,'shelf','assemble');act(e,'shelf','handle');act(e,'bedroomDoor','wind');}
function hall(e:GameEngine){at(e,'notice');at(e,'photo');act(e,'hooks','hook','Star');act(e,'keyCabinet','cabinet');act(e,'livingDoor','living');act(e,'kitchenDoor','kitchen');}
function living(e:GameEngine){act(e,'batteries','battery');act(e,'remote','remote');act(e,'tv','play');at(e,'diagram');act(e,'studyDoor','code','2413');}
function kitchen(e:GameEngine){at(e,'receipt');act(e,'magnet','magnet');act(e,'pantry','tin','Tea');act(e,'utilityDoor','utility');}
function finish(e:GameEngine){act(e,'sheet','sheet');act(e,'floorPlan','overlay',true);at(e,'deskNote');act(e,'drawer','code','1806');at(e,'legend');act(e,'console','insertTool');act(e,'console','sequence',['Hall','Rooms','Entrance']);at(e,'bedsideNote');act(e,'suitcases','suitcase','Home');act(e,'entrance','insertKey');act(e,'entrance','manual','Manual');act(e,'entrance','pull');e.release('p1');}
for(const count of[1,2,4])for(const order of['living-first','kitchen-first'])test(`${count} players complete the apartment, ${order}`,()=>{const e=make(count);bedroom(e);hall(e);if(order==='living-first'){living(e);kitchen(e);}else{kitchen(e);living(e);}finish(e);assert.equal(e.state.doors.length,7);assert.equal(e.state.clues.length,11);assert.equal(e.state.phase,'playing');for(const p of e.state.players){p.x=712;p.y=1780;}e.tick();assert.equal(e.state.phase,'won');assert.ok(e.has('reunion'));});
test('wrong answers and missing items are recoverable',()=>{const e=make();at(e,'shelf');assert.throws(()=>e.act('p1','shelf','assemble'),/seat/);bedroom(e);hall(e);at(e,'studyDoor');assert.throws(()=>e.act('p1','studyDoor','code','9999'),/does not match/);assert.equal(e.has('study'),false);living(e);kitchen(e);act(e,'sheet','sheet');act(e,'floorPlan','overlay',true);act(e,'drawer','code','1806');act(e,'console','insertTool');assert.throws(()=>act(e,'console','sequence',['Entrance','Rooms','Hall']),/reset/);act(e,'console','sequence',['Hall','Rooms','Entrance']);assert.ok(e.has('backup'));});
test('shared item and door effects happen once; occupied mechanism cannot be stolen',()=>{const e=make(2);at(e,'seat');const o=APARTMENT.interactables.find(o=>o.id==='seat')!;Object.assign(e.player('p2'),{x:o.x,y:o.y});assert.equal(e.inspect('p2','seat').lockedBy,'Child 1');assert.throws(()=>e.act('p2','seat','collectSeat'),/friend/);e.act('p1','seat','collectSeat');e.act('p1','seat','collectSeat');assert.equal(e.state.inventory.filter(i=>i.id==='seat').length,1);e.disconnect('p1');e.inspect('p2','seat');e.act('p2','seat','collectSeat');assert.equal(e.state.inventory.length,1);assert.equal(e.state.hostId,'p2');});
test('validates distance, walls, action ownership and movement',()=>{const e=make();assert.throws(()=>e.inspect('p1','entrance'),/closer/);Object.assign(e.player('p1'),{x:631,y:464});assert.throws(()=>e.inspect('p1','bedroomDoor'),/closer/);at(e,'seat');assert.throws(()=>e.act('p1','seat','pull'),/does not belong/);e.release('p1');Object.assign(e.player('p1'),APARTMENT.spawn);e.input('p1',{x:999999,y:0,seq:1});e.tick();assert.ok(Math.abs(e.player('p1').x-APARTMENT.spawn.x)<=7.51);assert.equal(walkable({x:120,y:170},[]),false);assert.equal(canSee({x:560,y:464},{x:644,y:464},[]),false);assert.equal(canSee({x:560,y:464},{x:644,y:464},['bedroom']),true);assert.equal(canSee({x:560,y:340},{x:644,y:340},['bedroom']),false);});
test('hints escalate and disconnected players do not block reunion',()=>{const e=make(2);assert.match(e.hint('p1'),/drawing/);assert.match(e.hint('p1'),/seat and legs/);assert.match(e.hint('p1'),/Collect/);assert.equal(e.hint('p1'),e.hint('p1'));bedroom(e);hall(e);living(e);kitchen(e);finish(e);e.player('p1').y=1780;e.disconnect('p2');assert.equal(e.state.phase,'won');});
test('all interactables and the finale are reachable through the physical apartment',()=>{
 const doors=APARTMENT.doors.map(d=>d.id),step=16,start={x:320,y:384};const queue=[start],seen=new Set([`${start.x},${start.y}`]);for(let i=0;i<queue.length;i++){const p=queue[i];for(const[dx,dy]of[[step,0],[-step,0],[0,step],[0,-step]]){const q={x:p.x+dx,y:p.y+dy},key=`${q.x},${q.y}`;if(seen.has(key)||!walkable(q,doors))continue;const moved=movePoint(p,dx,dy,doors);if(Math.hypot(moved.x-q.x,moved.y-q.y)>1)continue;seen.add(key);queue.push(q);}}
 for(const o of APARTMENT.interactables)assert.ok(queue.some(p=>Math.hypot(p.x-o.x,p.y-o.y)<70&&canSee(p,o,doors,70)),`Unreachable: ${o.id}`);
 assert.ok(queue.some(p=>p.y>1760),'Cannot reach outside');
});
test('visibility never shows distant or walled-off players',()=>{assert.equal(canSee({x:300,y:300},{x:700,y:300},APARTMENT.doors.map(d=>d.id)),false);assert.equal(canSee({x:640,y:650},{x:860,y:650},APARTMENT.doors.map(d=>d.id)),false);});
test('client-predicted positions are accepted when reachable and rejected through walls',()=>{const e=make();const p=e.player('p1');const start={x:p.x,y:p.y};assert.equal(e.position('p1',{x:start.x+10,y:start.y,dir:'right',moving:true,run:false,seq:1}),true);assert.equal(p.x,start.x+10);assert.equal(p.direction,'right');assert.equal(p.moving,true);
 // Teleporting far away is refused.
 assert.equal(e.position('p1',{x:1500,y:1500,moving:true}),false);assert.equal(p.x,start.x+10);
 // Walking through the closed bedroom door into the hall is refused even if the distance is small.
 p.x=570;p.y=464;e.moved.set('p1',Date.now()-200);assert.equal(e.position('p1',{x:630,y:464,moving:true}),false);assert.equal(p.x,570);
 // Once the door is open the same step is fine.
 e.state.doors.push('bedroom');e.moved.set('p1',Date.now()-200);assert.equal(e.position('p1',{x:630,y:464,moving:true,run:true}),true);assert.equal(p.running,true);});
test('objectives follow puzzle progress',()=>{const e=make();assert.deepEqual(e.state.objectives,['Find a way to open your bedroom door.']);e.flag('bedroom');e.tick();assert.equal(e.state.objectives[0],'Search the hallway for the cabinet key.');e.flag('cabinet');e.flag('living');e.flag('kitchen');e.tick();assert.equal(e.state.objectives.length,2);});
