import test from 'node:test';
import assert from 'node:assert/strict';
import { Client, type Room } from 'colyseus.js';
import { APARTMENT, canSee, walkable, movePoint } from '../../shared/map';
import type { Point, Snapshot, Inspection } from '../../shared/types';
const base=process.env.TEST_SERVER_URL??'http://127.0.0.1:2567',client=new Client(base.replace(/^http/,'ws'));
type Peer={room:Room;state?:Snapshot;views:Inspection[];feedback:{message:string;good:boolean}[];seq:number};
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function until(fn:()=>boolean,timeout=8000){const end=Date.now()+timeout;while(!fn()){if(Date.now()>end)throw Error('Timed out waiting for game state');await delay(35);}}
async function join(name:string,code?:string):Promise<Peer>{const r=await fetch(`${base}/api/rooms${code?`/${code}/join`:''}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});assert.equal(r.ok,true);const room=await client.consumeSeatReservation(await r.json()),p:Peer={room,views:[],feedback:[],seq:0};room.onMessage('snapshot',(s:Snapshot)=>p.state=s);room.onMessage('inspection',(v:Inspection)=>p.views.push(v));room.onMessage('feedback',(f:any)=>p.feedback.push(f));await until(()=>!!p.state);return p;}
function route(start:Point,target:Point,doors:string[],exact=false):Point[]{
 const step=16,origin={x:Math.round(start.x/step)*step,y:Math.round(start.y/step)*step};const nodes=[origin],parents=[-1],seen=new Set([`${origin.x},${origin.y}`]);let end=-1;
 for(let i=0;i<nodes.length;i++){const p=nodes[i];if(Math.hypot(p.x-target.x,p.y-target.y)<(exact?12:62)&&canSee(p,target,doors,exact?20:80)){end=i;break;}for(const[dx,dy]of[[step,0],[-step,0],[0,step],[0,-step]]){const q={x:p.x+dx,y:p.y+dy},key=`${q.x},${q.y}`;if(seen.has(key)||!walkable(q,doors,13))continue;const moved=movePoint(p,dx,dy,doors);if(Math.hypot(q.x-moved.x,q.y-moved.y)>1)continue;seen.add(key);nodes.push(q);parents.push(i);}}
 if(end<0)throw Error(`No physical route to ${target.x},${target.y}`);const path:Point[]=[];while(end>=0){path.unshift(nodes[end]);end=parents[end];}return path.filter((p,i)=>i===0||i===path.length-1||(p.x-path[i-1].x)!==(path[i+1].x-p.x)||(p.y-path[i-1].y)!==(path[i+1].y-p.y));
}
async function follow(peers:Peer[],points:Point[]){for(const point of points){const end=Date.now()+25000;while(true){if(peers.every(p=>p.state?.phase==='won'))break;let arrived=true;for(const p of peers){const me=p.state!.players.find(v=>v.id===p.room.sessionId)!;const dx=point.x-me.x,dy=point.y-me.y,n=Math.hypot(dx,dy);if(n>6)arrived=false;p.room.send('move',{x:n>6?dx/Math.max(n,10):0,y:n>6?dy/Math.max(n,10):0,seq:++p.seq});}if(arrived)break;if(Date.now()>end)throw Error(`Walking blocked near ${JSON.stringify(point)}: ${JSON.stringify(peers[0].state!.players[0])}`);await delay(50);}}for(const p of peers)p.room.send('move',{x:0,y:0,seq:++p.seq});await delay(75);}
test('four players physically walk the entire apartment and escape together',{timeout:300000},async()=>{
 const peers:Peer[]=[];try{const a=await join('Lead');peers.push(a);for(let i=2;i<=4;i++)peers.push(await join(`Friend ${i}`,a.state!.roomCode));a.room.send('start');await until(()=>peers.every(p=>p.state?.phase==='playing'));
 async function use(id:string,action?:string,value?:unknown){const o=APARTMENT.interactables.find(o=>o.id===id)!;const me=a.state!.players.find(p=>p.id===a.room.sessionId)!;await follow(peers,route(me,o,a.state!.doors));const actor=peers[peers.length===4?Math.floor(Math.random()*4):0];let n=actor.views.length;actor.room.send('inspect',id);await until(()=>actor.views.length>n);if(action){n=actor.feedback.length;actor.room.send('action',{target:id,action,value});await until(()=>actor.feedback.length>n);assert.equal(actor.feedback.at(-1)!.good,true,`${id}: ${actor.feedback.at(-1)!.message}`);}actor.room.send('close');await delay(65);}
 await use('toyHouse');await use('seat','collectSeat');await use('legs','collectLegs');await use('shelf','assemble');await use('shelf','handle');await use('bedroomDoor','wind');console.log('Bedroom escaped through normal movement.');
 await use('notice');await use('photo');await use('hooks','hook','Star');await use('keyCabinet','cabinet');await use('kitchenDoor','kitchen');await use('receipt');await use('magnet','magnet');await use('pantry','tin','Tea');await use('utilityDoor','utility');console.log('Kitchen branch completed.');
 await use('livingDoor','living');await use('batteries','battery');await use('remote','remote');await use('tv','play');await use('diagram');await use('studyDoor','code','2413');await use('sheet','sheet');await use('floorPlan','overlay',true);await use('deskNote');await use('drawer','code','1806');console.log('Study and cross-room clues completed.');
 await use('legend');await use('console','insertTool');await use('console','sequence',['Hall','Rooms','Entrance']);await use('bedsideNote');await use('suitcases','suitcase','Home');await use('entrance','insertKey');await use('entrance','manual','Manual');await use('entrance','pull');
 await follow(peers,route(a.state!.players.find(p=>p.id===a.room.sessionId)!,{x:712,y:1780},a.state!.doors,true));await until(()=>peers.every(p=>p.state?.phase==='won'));assert.ok(peers.every(p=>p.state!.doors.length===7));console.log('All four clients reached the reunion.');
 }finally{await Promise.allSettled(peers.map(p=>p.room.leave()));}
});
