import type { Clue, Item, PuzzleDefinition } from '../shared/types';
export const ITEMS:Record<string,Item>={
 seat:{id:'seat',name:'Stool seat',description:'A round wooden seat with four threaded sockets underneath.',icon:'▱'},
 legs:{id:'legs',name:'Four stool legs',description:'Short wooden legs. Their threads match the stool seat.',icon:'⋒'},
 handle:{id:'handle',name:'Winding handle',description:'A square-ended handle for the bedroom’s manual release.',icon:'⚙'},
 cabinetKey:{id:'cabinetKey',name:'Cabinet key',description:'A tiny brass key, hidden behind the star hook.',icon:'⚿'},
 livingKey:{id:'livingKey',name:'Living-room key',description:'A brass manual-release key with a leaf-shaped tag.',icon:'⚿'},
 kitchenKey:{id:'kitchenKey',name:'Kitchen key',description:'A manual-release key with a cup-shaped tag.',icon:'⚿'},
 batteries:{id:'batteries',name:'Two AA batteries',description:'Still sealed. The remote needs both.',icon:'▰'},
 magnet:{id:'magnet',name:'Magnet on a string',description:'A souvenir fishing magnet from the fridge.',icon:'∩'},
 utilityKey:{id:'utilityKey',name:'Utility key',description:'Retrieved from the bottom of the tea tin.',icon:'⚿'},
 sheet:{id:'sheet',name:'Transparent service sheet',description:'A tracing sheet with three linked circles and alignment marks.',icon:'▱'},
 tool:{id:'tool',name:'Emergency release tool',description:'A T-shaped service tool with a triangular tip.',icon:'⚒'},
 override:{id:'override',name:'Entrance override key',description:'The mechanical backup key, kept in the blue suitcase.',icon:'⚿'}
};
export const CLUES:Record<string,Clue>={
 toyHouse:{id:'toyHouse',title:'A house inside a house',room:'bedroom',text:'Your toy-house sketch has a little arrow: “Real door’s hatch → beside the door, down low.” Below it: “Square handle on the high shelf. Stool legs screw into the round seat.”'},
 notice:{id:'notice',title:'Door-system maintenance notice',room:'hall',text:'APARTMENT 07 · TEMPORARY SERVICE NOTICE\nThe retrofit access system is awaiting repair. A storm-triggered controller fault may hold the internal latches. Manual releases remain usable.\nBedroom: winding handle. Living / kitchen / utility: labelled keys. Study: local PIN. Main bedroom: backup power release. Entrance: mechanical override after backup is restored.\nDO NOT RESET THE SYSTEM UNTIL THE BACKUP ROUTE IS IDENTIFIED.'},
 photo:{id:'photo',title:'A familiar hiding place',room:'hall',text:'In the photograph, Mum hangs the little cabinet key behind the STAR-shaped coat hook. “So we always know where it is.” The other hooks are a moon, a leaf and a circle.'},
 recording:{id:'recording',title:'Recorded maintenance instructions',room:'living',text:'The TV has a small battery backup. Its saved service recording plays:\n“Your study release follows the route from where you SLEEP, to where you EAT, to where you READ, and finally where you ARRIVE. Use the section numbers on the framed apartment diagram.”\nA timestamp shows the recording was made yesterday. This problem was already being repaired.'},
 diagram:{id:'diagram',title:'Numbered apartment sections',room:'living',text:'A small floor-plan legend: STUDY / READ = 1 · BEDROOM / SLEEP = 2 · HALL / ARRIVE = 3 · KITCHEN / EAT = 4. Four symbols appear on the study panel.'},
 receipt:{id:'receipt',title:'Grocery receipt · 18 June',room:'kitchen',text:'SHOPPING · 18/06\nFlour, rice, tea, sugar.\nBeside TEA, Dad has written: “Spare utility key tucked below the false bottom. Use the fridge fishing magnet.”\nOn the back: “New desk lock set today. DDMM. I will remember this one.”'},
 deskNote:{id:'deskNote',title:'A note beside the desk',room:'study',text:'“The desk code is the day and month on the grocery receipt when I fitted the new lock. Four digits, DDMM. The release tool is in the drawer. Match the tracing sheet’s corners to the floor plan before touching the service controls.”'},
 route:{id:'route',title:'The backup route',room:'study',text:'With the transparent sheet aligned, three arrows connect HALL → ROOMS → ENTRANCE. These are the service-console controls, in that order. The entrance remains mechanically secured until its override key is used.'},
 legend:{id:'legend',title:'Service-console status legend',room:'utility',text:'Triangle slot: insert emergency tool. Press the three areas in the maintenance route’s order. AMBER / dotted ring = waiting. GREEN / tick = accepted. Confirm only when all three controls show a tick. A wrong sequence can be cleared and retried.'},
 bedsideNote:{id:'bedsideNote',title:'Mum’s reminder',room:'parents',text:'“Entrance spare is inside the suitcase tagged HOME, beneath the folded lining. Not the WORK or HOLIDAY bag. The instruction card is with it. I am only stepping into the corridor to meet the repair person.”'},
 finalCard:{id:'finalCard',title:'Entrance override instructions',room:'parents',text:'1. Restore backup service.\n2. Insert the entrance override key.\n3. Turn selector from AUTO to MANUAL.\n4. Pull the release handle.\nFrom the other side of the door: “I am here. Take your time. You are doing really well.”'}
};
export const PUZZLES:PuzzleDefinition[]=[
 {id:'bedroom',goal:'Find a way to open your bedroom door.',prerequisites:[],actions:['collectSeat','collectLegs','assemble','handle','wind'],completion:'bedroom',rewards:['handle','bedroom door'],hints:['There is a drawing on the little desk.','The stool needs both its seat and legs. Take them to the high shelf.','Collect the seat and legs, assemble at the shelf, retrieve the handle, then wind the hatch beside the door.']},
 {id:'hall',goal:'Search the hallway for the cabinet key.',prerequisites:['bedroom'],actions:['hook','cabinet','living','kitchen'],completion:'cabinet',rewards:['livingKey','kitchenKey'],hints:['The family photograph shows an old habit.','Look behind the same coat hook shown in the photograph.','Choose the STAR hook, use its key on the cabinet, then use the labelled keys on the living-room and kitchen releases.']},
 {id:'studyDoor',goal:'Work out the code for the study panel.',prerequisites:['living'],actions:['battery','remote','play','code'],completion:'study',rewards:['study door'],hints:['Something in the living room can explain the four-symbol panel.','Power the remote and play the TV recording. Match its route to the framed section numbers.','Sleep → Eat → Read → Arrive becomes 2 → 4 → 1 → 3. Enter 2413 at the study panel.']},
 {id:'utilityDoor',goal:'Get into the utility room past the kitchen.',prerequisites:['kitchen'],actions:['magnet','tin','utility'],completion:'utility',rewards:['utilityKey','utility door'],hints:['Someone wrote on the shopping receipt.','The tea tin has a false bottom; the fridge has a useful souvenir.','Collect the fridge magnet, select TEA in the pantry, retrieve the key and use it on the utility door.']},
 {id:'backup',goal:'Restore the backup power.',prerequisites:['study','utility'],actions:['sheet','overlay','drawer','insertTool','sequence'],completion:'backup',rewards:['parents door','backup lighting'],hints:['The study contains both a tool and instructions.','Align the tracing sheet with the plan. The drawer code comes from the kitchen receipt date.','Use 1806 on the desk drawer, align the sheet, insert the tool at the utility console, then press Hall → Rooms → Entrance and confirm.']},
 {id:'entrance',goal:'Open the front door and reach Mum together.',prerequisites:['backup'],actions:['suitcase','insertKey','manual','pull'],completion:'exit',rewards:['escape'],hints:['Mum kept one last backup in her bedroom.','Read the bedside note and check the luggage tags.','Open the HOME suitcase, take the override key, insert it at the entrance, choose MANUAL, then pull the handle. Everyone must reach the exit.']}
];
